apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: houses.rug.nl
spec:
  group: rug.nl
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                address:
                  type: string
                houseNumber:
                  type: string
                squareMeters:
                  type: integer
  scope: Namespaced
  names:
    plural: houses
    singular: house
    kind: House
    shortNames:
    - ho