apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: rug-node-exporter
  labels:
    app: rug-node-exporter
spec:
  selector:
    app: rug-node-exporter
  ports:
  - name: web
    port: 3000